# This is a basic workflow to help you get started with Actions

name: Check PKGBUILD builds for Arch.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  PKGBUILD-build:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          pacman-key --init
          pacman -Syu --noconfirm

      - name: Add builduser
        run: |
          # Create the builduser
          useradd builduser -m
          # Delete the buildusers password
          passwd -d builduser
          # Allow the builduser passwordless sudo
          printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers

      - name: Check out sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: swaync

      - name: Test PKGBUILD
        run: |
          cd swaync
          build_dir="/tmp/PKGBUILD-git"
          cd build-scripts

          mkdir $build_dir
          cp ./PKGBUILD-git $build_dir/PKGBUILD

          mkdir $build_dir/src
          cp -r ../ $build_dir/src/swaync

          cd $build_dir
          sudo chown -R builduser $build_dir
          # Use the locally checked-out branch instead of downloading the source
          sudo -H -u builduser bash -c "makepkg -s --noconfirm --noextract SRCDEST=$build_dir"
